### ISSUE TITLE
Super Mario

### ISSUE THREAD

**Issue by YEGANE1370** [schrum2/GameGAN#17]
Hi, I want to create new supermario levels with a new latenet vector and use it as input in the Mario-AI-Framework/src/PlayLevel.java code.
In fact, I need the character form of the levels in format .txt.
How can I get the character from the latene vector? Which part of the code is this related to?
Is there a need to install a program?

**Comment by schrum2** [comment]
Something here can probably help you:
https://github.com/schrum2/GameGAN/blob/master/src/edu/southwestern/tasks/mario/gan/MarioGANUtil.java

**Comment by YEGANE1370** [comment]
Thanks for the reply.
Actually, I need the character form of the steps that is in the VGLC file.
Does this link that you sent have the output in the format I want?

**Comment by schrum2** [comment]
I think the conversions are all in the opposite direction, but I recommend looking at this file:
https://github.com/schrum2/GameGAN/blob/master/src/edu/southwestern/tasks/mario/level/MarioLevelUtil.java
Also look at the files it is related to, such as LevelParser and OldLevelParser, but this depends on which version you want.

The method listLevelFromVGLCFile basically does the opposite conversion, so maybe you can reverse it.
